"use client";
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Tooltip, CartesianGrid } from 'recharts';
import { money } from '@/lib/calculations/budget';
import type { Transaction } from '@/types';
export function SpendingChart({ transactions, start, end }: {
    transactions: Transaction[];
    start: string;
    end?: string;
}) { const days = Array.from({ length: end ? Math.max(1, Math.ceil((new Date(end).getTime()-new Date(start).getTime())/86400000)) : 7 }, (_, i) => { const date = new Date(new Date(start).getTime() + i * 86400000); return { name: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'Asia/Manila' }), amount: transactions.filter(t => t.kind === 'expense' && new Date(t.date) >= date && new Date(t.date).getTime() < date.getTime() + 86400000).reduce((s, t) => s + t.amount, 0) }; }); return <div className="chart-container" role="img" aria-label={days.map(d => d.name + ': ' + money(d.amount)).join(', ')}><ResponsiveContainer width="100%" height="100%"><BarChart data={days} margin={{ left: -20, right: 5, top: 12 }}><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="var(--border)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--muted-foreground)' }} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--muted-foreground)' }} tickFormatter={n => '₱' + n / 100}/><Tooltip formatter={(n) => money(Number(n))} itemStyle={{ color: 'var(--foreground)' }} labelStyle={{ color: 'var(--foreground)' }} cursor={{ fill: 'var(--muted)' }} contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', background: 'var(--popover)', color: 'var(--popover-foreground)' }}/><Bar maxBarSize={28} name="Spent" dataKey="amount" fill="var(--chart-1)" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div>; }
