import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';import {reset,signIn} from './runtime.mjs';import {cycleDates,totals} from '../lib/calculations/budget.ts';import {amount} from '../lib/validation/schemas.ts';import {getBudget,receiveAllowance} from '../services/budget-service.ts';import {addTransaction,deleteExpense,editExpense} from '../services/transaction-service.ts';import {POST as saveProfile} from '../app/api/profile/route.ts';import {POST as saveGoal} from '../app/api/savings-goals/route.ts';import {GET as getCycle} from '../app/api/budget-cycles/route.ts';import {POST as saveTransaction} from '../app/api/transactions/route.ts';import {POST as saveCategory,PATCH as archiveCategory} from '../app/api/categories/route.ts';
let sql;beforeEach(async()=>{sql=await reset()});
const req=(path,body)=>new Request('https://alloca.test/api/'+path,{method:'POST',headers:{origin:'https://alloca.test','content-type':'application/json'},body:JSON.stringify(body)});
async function setup(id='alice'){signIn(id);const r=await saveProfile(req('profile',{name:id,allowance:1500}));assert.equal(r.status,200);return getBudget(id)}
test('money is stored in exact centavos and rejects invalid precision',()=>{assert.equal(amount.parse('12.34'),1234);for(const v of [0,-2,Infinity,'abc',1.001,1000001])assert.equal(amount.safeParse(v).success,false)});
test('Philippine Monday reset handles UTC boundary and year boundary',()=>{assert.deepEqual(cycleDates(new Date('2026-09-06T16:00:00Z')),{start:'2026-09-06T16:00:00.000Z',end:'2026-09-13T16:00:00.000Z'});assert.equal(cycleDates(new Date('2026-09-06T15:59:59Z')).start,'2026-08-30T16:00:00.000Z');assert.equal(cycleDates(new Date('2026-01-01T00:00:00Z')).start,'2025-12-28T16:00:00.000Z')});
test('register initializes six categories and creates no phantom income',async()=>{const d=await setup();assert.equal(d.categories.length,6);assert.equal(d.transactions.length,0);assert.equal(d.profile.allowance,150000);await setup();assert.equal((await getBudget('alice')).categories.length,6)});
test('allowance is received once, extra income and expenses calculate correctly',async()=>{await setup();await receiveAllowance('alice');await assert.rejects(()=>receiveAllowance('alice'),/already/);await addTransaction('alice',{kind:'income',amount:200,category:'Extra income',note:'Tutoring'});await addTransaction('alice',{kind:'expense',amount:80.50,category:'Meals'});const d=await getBudget('alice');assert.equal(totals(d.transactions).available,161950)});
test('savings deposits debit spendable balance; withdrawals restore it and cannot overdraw',async()=>{await setup();await receiveAllowance('alice');assert.equal((await saveGoal(req('savings-goals',{name:'Laptop',target:10000}))).status,200);let d=await getBudget('alice');const goalId=d.goals[0].id;await addTransaction('alice',{kind:'saving',amount:500,category:'Savings',goalId});await assert.rejects(()=>addTransaction('alice',{kind:'saving',amount:1100,category:'Savings',goalId}),/Insufficient/);await addTransaction('alice',{kind:'withdrawal',amount:100,category:'Savings',goalId});await assert.rejects(()=>addTransaction('alice',{kind:'withdrawal',amount:401,category:'Savings',goalId}),/Insufficient/);d=await getBudget('alice');assert.equal(d.goals[0].saved,40000);assert.equal(totals(d.transactions).available,110000)});
test('user ownership blocks reading and editing another account’s money',async()=>{await setup('alice');await addTransaction('alice',{kind:'expense',amount:50,category:'Meals'});const a=await getBudget('alice');await setup('bob');assert.equal((await getBudget('bob')).transactions.length,0);await assert.rejects(()=>deleteExpense('bob',a.transactions[0].id),/Only expenses/);await assert.rejects(()=>editExpense('bob',a.transactions[0].id,{kind:'expense',amount:10,category:'Meals'}),/Only current/)});
test('expense edits and deletes restore accurate totals',async()=>{await setup();await receiveAllowance('alice');await addTransaction('alice',{kind:'expense',amount:100,category:'Meals'});let d=await getBudget('alice');const id=d.transactions.find(t=>t.kind==='expense').id;await editExpense('alice',id,{kind:'expense',amount:70,category:'Transport'});assert.equal(totals((await getBudget('alice')).transactions).available,143000);await deleteExpense('alice',id);assert.equal(totals((await getBudget('alice')).transactions).available,150000)});
test('rollover preserves previous history and surplus without inventing allowance',async()=>{await setup();await receiveAllowance('alice');await addTransaction('alice',{kind:'expense',amount:400,category:'Meals'});const old=(await getBudget('alice')).cycle;await sql.prepare('UPDATE cycles SET start=?,end=? WHERE id=?').run(new Date(new Date(old.start).getTime()-7*86400000).toISOString(),old.start,old.id);const d=await getBudget('alice');assert.notEqual(d.cycle.id,old.id);assert.equal(d.cycle.carry,110000);assert.equal(d.cycles.length,2);assert.equal(d.transactions.filter(t=>t.cycle_id===d.cycle.id).length,0);await assert.rejects(()=>deleteExpense('alice',d.transactions.find(t=>t.kind==='expense').id),/Only expenses/)});
test('API rejects anonymous and cross-origin mutations and validates inputs',async()=>{signIn(null);assert.equal((await getCycle(new Request('https://alloca.test/api/budget-cycles'))).status,401);await setup();const cross=new Request('https://alloca.test/api/transactions',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'});assert.equal((await saveTransaction(cross)).status,403);assert.equal((await saveTransaction(req('transactions',{kind:'expense',amount:-10,category:'Meals'}))).status,400)});
test('category archive blocks new expenses but retains history and restores cleanly',async()=>{const d=await setup();await addTransaction('alice',{kind:'expense',amount:100,category:'Meals'});const id=d.categories.find(c=>c.name==='Meals').id;assert.equal((await archiveCategory(new Request('https://alloca.test/api/categories?id='+id,{method:'PATCH'}))).status,200);await assert.rejects(()=>addTransaction('alice',{kind:'expense',amount:50,category:'Meals'}),/active category/);assert.equal((await getBudget('alice')).transactions.length,1);assert.equal((await saveCategory(req('categories',{name:'Meals',color:'#087f72'}))).status,400);await archiveCategory(new Request('https://alloca.test/api/categories?id='+id,{method:'PATCH'}));await addTransaction('alice',{kind:'expense',amount:50,category:'Meals'});assert.equal((await getBudget('alice')).transactions.length,2)});
