"use client";
import { useState } from 'react';
import { Search } from 'lucide-react';
import { useBudget } from '@/hooks/use-budget';
import { PageHeader } from '@/components/shared/page-header';
import { DataGate } from '@/components/shared/data-gate';
import { Choice } from '@/components/shared/choice';
import { TransactionDialog } from './transaction-dialog';
import { TransactionList } from './transaction-list';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { money, totals } from '@/lib/calculations/budget';
export function ExpensesPage() { const { data } = useBudget(); const [tab, setTab] = useState('all'), [search, setSearch] = useState(''), [period, setPeriod] = useState('week'), [category, setCategory] = useState('all'); const base = data?.transactions.filter(t => period === 'all' || t.cycle_id === data.cycle.id) || []; const filtered = base.filter(t => (tab === 'all' || (tab === 'income' ? ['income', 'allowance'].includes(t.kind) : tab === 'saving' ? ['saving', 'withdrawal'].includes(t.kind) : t.kind === tab)) && (category === 'all' || t.category === category) && (t.note + ' ' + t.category).toLowerCase().includes(search.toLowerCase())); const total = totals(base); return <DataGate><PageHeader title="Every little thing, accounted for." description="Your allowance, your coffee runs, your progress. All in one place." actions={<><TransactionDialog kind="income"/><TransactionDialog /></>}/><div className="mini-stats"><div><span>Money received</span><strong>{money(total.income)}</strong></div><div><span>Everyday spending</span><strong>{money(total.spent)}</strong></div><div><span>Net savings transfers</span><strong>{money(total.saved)}</strong></div></div><section className="card"><div className="filter-bar"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="expense">Expenses</TabsTrigger><TabsTrigger value="income">Income</TabsTrigger><TabsTrigger value="saving">Savings</TabsTrigger></TabsList></Tabs><Choice label="Time period" value={period} onChange={setPeriod} options={[{ value: 'week', label: 'This week' }, { value: 'all', label: 'All time' }]}/></div><div className="filter-bar"><label className="search-field"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your transactions" aria-label="Search transactions"/></label><Choice label="Filter category" value={category} onChange={setCategory} options={[{ value: 'all', label: 'All categories' }, ...(data?.categories ?? []).map(c => ({ value: c.name, label: c.name }))]}/></div><TransactionList transactions={filtered} editable/>{base.length > 0 && !filtered.length && <p className="muted small">No matches. Try a different filter.</p>}<p className="table-note">{filtered.length} transactions · Current-week expenses can be edited or deleted. Completed weeks remain in your history.</p></section></DataGate>; }
