import { sql } from "drizzle-orm";
import { sqliteTable, text, integer, index, uniqueIndex, check } from "drizzle-orm/sqlite-core";
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),allowance:integer('allowance').notNull().default(0),frequency:text('frequency').notNull().default('weekly'),created:text('created').notNull()});
export const cycles=sqliteTable('cycles',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),start:text('start').notNull(),end:text('end').notNull(),carry:integer('carry').notNull().default(0),frequency:text('frequency').notNull().default('weekly')},t=>[uniqueIndex('cycles_user_start').on(t.userId,t.start)]);
export const categories=sqliteTable('categories',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),name:text('name').notNull(),color:text('color').notNull(),archived:integer('archived').notNull().default(0)},t=>[uniqueIndex('categories_user_name').on(t.userId,t.name)]);
export const goals=sqliteTable('goals',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),name:text('name').notNull(),target:integer('target').notNull(),due:text('due'),created:text('created').notNull()},t=>[index('goals_user').on(t.userId),check('positive_target',sql`${t.target} > 0`)]);
export const transactions=sqliteTable('transactions',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),cycleId:text('cycle_id').notNull().references(()=>cycles.id),kind:text('kind').notNull(),amount:integer('amount').notNull(),category:text('category').notNull(),note:text('note').notNull(),date:text('date').notNull(),goalId:text('goal_id').references(()=>goals.id)},t=>[uniqueIndex('transactions_one_allowance_per_cycle').on(t.userId,t.cycleId).where(sql`${t.kind} = 'allowance'`),index('transactions_user_date').on(t.userId,t.date),index('transactions_cycle').on(t.cycleId),index('transactions_goal').on(t.goalId),check('positive_amount',sql`${t.amount} > 0`),check('valid_kind',sql`${t.kind} IN ('expense','income','allowance','saving','withdrawal')`)]);

export const syncOperations=sqliteTable('sync_operations',{id:text('id').notNull(),userId:text('user_id').notNull().references(()=>profiles.id),payload:text('payload').notNull(),appliedAt:text('applied_at').notNull()},t=>[uniqueIndex('sync_operations_user_id').on(t.userId,t.id)]);
