import type {BudgetData} from '@/types';import type {OfflineStatus} from './types';import {readRecord,updateRecord,clearOffline} from './storage';import {localView,strictView,applyLocal,makeOperation} from './reducer';
export const status:OfflineStatus={online:true,pending:0,syncing:false,message:'',ready:false,needsLogin:false};let inFlight:Promise<void>|undefined;
export function notify(){window.dispatchEvent(new Event('alloca-status'))}
export async function network(path:string,method='GET',body?:unknown){const response=await fetch('/api/'+path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});const value=await response.json();if(!response.ok||value.error){const e=new Error(value.error||'Unable to sync.') as Error&{status:number};e.status=response.status;throw e}return value;}
export async function cachedBudget(){const record=await readRecord();status.pending=record?.queue.length||0;status.ready=!!record;notify();return record?localView(record):null;}
async function syncWork(){status.online=navigator.onLine;if(!status.online){notify();return}status.syncing=true;notify();try{
 let record=await readRecord();const remote=await network('budget-cycles');status.needsLogin=false;
 if(remote.needsSetup){if(record)throw new Error('Sign in to the saved account to sync its changes.');return}
 if(record&&record.userId!==remote.profile.id){throw new Error('A different account is signed in. Return to the saved account, or export and clear its offline data first.')}
 if(!record){await updateRecord(()=>({record:{version:1,userId:remote.profile.id,base:remote,queue:[],updatedAt:new Date().toISOString()},result:null}));record=await readRecord()}
 if(!record)return;
 if(!record.queue.length){await updateRecord(old=>({record:old&&old.userId===remote.profile.id&&!old.queue.length?{...old,base:remote,updatedAt:new Date().toISOString(),conflict:undefined}:old,result:null}));}
 else{let count=0;while(count++<1000){record=await readRecord();const operation=record?.queue[0];if(!record||!operation)break;try{const result=await network('sync','POST',operation);if(result.ack!==operation.id||result.data?.profile?.id!==record.userId)throw new Error('Sync response could not be verified.');await updateRecord(old=>{if(!old||old.userId!==operation.userId||old.queue[0]?.id!==operation.id)return {record:old,result:null};const next={...old,base:result.data,queue:old.queue.slice(1),updatedAt:new Date().toISOString(),conflict:undefined as string|undefined};try{next.draft=strictView(next)}catch{next.conflict='Your server budget changed while this device was offline. Review and resolve the pending changes.'}return {record:next,result:null}})}catch(e){const error=e as Error&{status?:number};if(error.status&&error.status<500&&error.status!==401&&error.status!==429){await updateRecord(old=>({record:old?{...old,conflict:error.message}:old,result:null}));}throw e}}}
 status.message='';status.online=true;
 }catch(e){const error=e as Error&{status?:number};status.needsLogin=error.status===401;status.message=status.needsLogin?'Reconnect your account to sync. Your saved budget is still available.':error.status?error.message:!navigator.onLine?'Offline. Changes are saved on this device.':error.message;status.online=navigator.onLine;
 }finally{status.syncing=false;const record=await readRecord();status.pending=record?.queue.length||0;status.ready=!!record;notify();window.dispatchEvent(new Event('alloca-data'));}}
export function sync(){if(inFlight)return inFlight;inFlight=(async()=>{if(navigator.locks)await navigator.locks.request('alloca-sync',syncWork);else await syncWork()})().finally(()=>{inFlight=undefined});return inFlight;}
export async function localRequest(path:string,method='GET',body?:unknown){if(method==='GET'){if(path==='budget-cycles'){const cached=await cachedBudget();if(cached){void sync();return cached}const remote=await network(path);if(!remote.needsSetup){await updateRecord(()=>({record:{version:1,userId:remote.profile.id,base:remote,queue:[],updatedAt:new Date().toISOString()},result:null}));void prepareStorage();}return remote}return network(path)}
 const existing=await readRecord();if(!existing)return network(path,method,body);
 await updateRecord(old=>{if(!old)throw new Error('Open your budget online before using offline mode.');if(old.conflict)throw new Error('Resolve the pending sync issue before adding more changes.');const current=localView(old);const operation=makeOperation(current,path,method as 'POST'|'PATCH'|'DELETE',(body||{}) as Record<string,unknown>);const draft=applyLocal(current,operation);const updated={...old,queue:[...old.queue,operation],draft};return {record:updated,result:null}});void sync();return {ok:true,local:true};}
export async function prepareStorage(){try{await navigator.storage?.persist()}catch{/* Browser may decline; readiness UI explains device storage. */}}
export async function exportOffline(){const record=await readRecord();if(!record)throw new Error('There is no offline budget to export.');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));a.download='alloca-offline-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export async function discardPending(){await updateRecord(old=>({record:old?{...old,queue:[],conflict:undefined}:null,result:null}));await sync();}
export async function beforeAccountSwitch(email?:string){const record=await readRecord();if(email&&record?.base.profile.email.toLowerCase()===email.trim().toLowerCase())return;if(record?.queue.length)throw new Error('You have unsynced changes. Return to your saved budget and sync them before switching accounts.');await clearOffline();}
