import type {BudgetData,Cycle} from '@/types';
import type {Operation,OfflineRecord} from './types';
import {cycleDates,totals} from '@/lib/calculations/budget';
import {transactionSchema,profileSchema,categorySchema,goalSchema} from '@/lib/validation/schemas';
export function rollCycle(data:BudgetData,at=new Date()):BudgetData{const dates=cycleDates(at);let c=data.cycles.find(c=>c.start===dates.start);if(!c){c={id:'local:'+dates.start,user_id:data.profile.id,...dates,carry:0};data.cycles.push(c)}let carry=0;data.cycles.sort((a,b)=>a.start.localeCompare(b.start));for(const cycle of data.cycles){cycle.carry=carry;carry=totals(data.transactions.filter(t=>t.cycle_id===cycle.id),carry).available}data.cycles.reverse();data.cycle=c;return data;}
export function applyLocal(input:BudgetData,op:Operation):BudgetData{if(input.profile.id!==op.userId)throw new Error('This change belongs to a different account.');const d=rollCycle(structuredClone(input),new Date(op.occurredAt));const url=new URL(op.path,'https://alloca.invalid/'),path=url.pathname.slice(1),id=url.searchParams.get('id');const fail=(s:string):never=>{throw new Error(s)};
 if(path==='transactions'){
  if(op.method==='POST'){const t=transactionSchema.parse(op.body);if(t.kind==='expense'&&!d.categories.some(c=>c.name===t.category&&!c.archived))fail('Choose an active category.');const goal=d.goals.find(g=>g.id===t.goalId);if(['saving','withdrawal'].includes(t.kind)&&!goal)fail('Savings goal not found.');const available=totals(d.transactions.filter(t=>t.cycle_id===d.cycle.id),d.cycle.carry).available;if(t.kind==='saving'&&t.amount>available)fail('Insufficient available balance for this transfer.');if(t.kind==='withdrawal'&&t.amount>(goal?.saved||0))fail('Insufficient savings for this withdrawal.');d.transactions.unshift({id:op.id,cycle_id:d.cycle.id,kind:t.kind,amount:t.amount,category:t.category,note:t.note,date:op.occurredAt,goal_id:t.goalId||null})}
  else{const t=d.transactions.find(t=>t.id===id&&t.kind==='expense'&&t.cycle_id===d.cycle.id);if(!t)fail('Only current-week expenses can be changed.');if(op.method==='DELETE')d.transactions=d.transactions.filter(t=>t.id!==id);else{const next=transactionSchema.parse(op.body);if(next.kind!=='expense'||!d.categories.some(c=>c.name===next.category&&!c.archived))fail('Choose an active category.');Object.assign(t!,{amount:next.amount,category:next.category,note:next.note})}}
 }else if(path==='budget-cycles'&&op.method==='POST'){if(d.transactions.some(t=>t.cycle_id===d.cycle.id&&t.kind==='allowance'))fail('You already recorded this week’s allowance.');d.transactions.unshift({id:op.id,cycle_id:d.cycle.id,kind:'allowance',amount:d.profile.allowance,category:'Allowance',note:'Weekly allowance',date:op.occurredAt,goal_id:null})}
 else if(path==='savings-goals'&&op.method==='POST'){const g=goalSchema.parse(op.body);d.goals.push({id:op.id,name:g.name,target:g.target,due:g.due||null,saved:0})}
 else if(path==='categories'&&op.method==='POST'){const c=categorySchema.parse(op.body);if(d.categories.some(x=>x.name.toLowerCase()===c.name.toLowerCase()))fail('A category with this name already exists.');d.categories.push({id:op.id,...c,archived:0})}
 else if(path==='categories'&&op.method==='PATCH'){const c=d.categories.find(c=>c.id===id);if(!c)fail('Category not found.');c!.archived=Number(op.body.archived)}
 else if(path==='profile'&&op.method==='POST'){const p=profileSchema.parse(op.body);Object.assign(d.profile,p)}
 else fail('This action requires an internet connection.');
 for(const g of d.goals)g.saved=d.transactions.filter(t=>t.goal_id===g.id).reduce((sum,t)=>sum+(t.kind==='saving'?t.amount:t.kind==='withdrawal'?-t.amount:0),0);
 return rollCycle(d,new Date(op.occurredAt));
}
export function strictView(record:OfflineRecord):BudgetData{let data=structuredClone(record.base);for(const op of record.queue)data=applyLocal(data,op);return rollCycle(data);}
export function makeOperation(data:BudgetData,path:string,method:Operation['method'],body:Record<string,unknown>={},date=new Date()):Operation{const op:Operation={id:crypto.randomUUID(),userId:data.profile.id,path,method,body:{...body},occurredAt:date.toISOString()};const url=new URL(path,'https://alloca.invalid/');const id=url.searchParams.get('id');if(url.pathname==='/transactions'&&method!=='POST'){const t=data.transactions.find(t=>t.id===id);if(t)op.before={amount:t.amount,category:t.category,note:t.note};}if(url.pathname==='/profile')op.before={name:data.profile.name,allowance:data.profile.allowance};if(url.pathname==='/categories'&&method==='PATCH'){const c=data.categories.find(c=>c.id===id);if(c){op.before={archived:c.archived};op.body.archived=1-c.archived}}return op;}

export function localView(record:OfflineRecord):BudgetData{try{return strictView(record)}catch(error){if(record.queue.length&&record.draft)return rollCycle(structuredClone(record.draft));throw error}}
